// {{{ 2 "SubmethodForwardDeclaration" ""
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 12 1 0 "46f7ba06_9b27_432f_99863594f4b8e980" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
UVDECONTAMINATIONSUB::CleanupAndSwitchLightOff();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=ch33$$valid=0$$time=2023-10-09 18:03$$checksum=dbe0e33d$$length=083$$