// {{{ 2 "SubmethodForwardDeclaration" ""
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 11 1 0 "c75429be_9abb_49e3_b65e9a1010f8e539" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHamHeaterShaker::StopShaker(HHS1);
// }} ""
// {{{ 12 1 0 "bc7efc11_4f5f_48a7_b2e8d9f6bca1baa2" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHamHeaterShaker::StopShaker(HHS2);
// }} ""
// {{{ 13 1 0 "46389e44_8261_4709_8e6a6a39afb24edb" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHamHeaterShaker::Terminate();
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Hamilton$$valid=0$$time=2023-12-19 14:55$$checksum=8bc3eb87$$length=087$$