// {{{ 2 "SubmethodForwardDeclaration" ""
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 26 1 0 "61db3eeb_eee1_41cd_9b82facd50c46350" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
SIASCENTRIFUGE::Terminate(intModuleID);
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=DWittmer$$valid=0$$time=2011-06-08 14:28$$checksum=aa6d6b65$$length=087$$